CREATE TABLE item (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    discountPrice DECIMAL(10, 2) NOT NULL,
    imageUrl VARCHAR(255) ,
    description TEXT NOT NULL,
    category VARCHAR(20) NOT NULL CHECK (category IN ('CATEGORY_ONE', 'CATEGORY_TWO', 'CATEGORY_THREE')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE', 'OUT_OF_STOCK', 'DISCONTINUED'))
);
